[jsons]
data = "https://raw.githubusercontent.com/syalia-srl/paris2024_data/main/data/predictions.json"
domains = "https://raw.githubusercontent.com/syalia-srl/paris2024_data/main/data/domains.json"

